### ISSUE TITLE
Ubuntu -  Namespace Hinoko not available - needs '--prefix /usr'

### ISSUE THREAD

**Issue by mungewell** [takaswie/libhinoko#3]
After building on Ubuntu 20:04 I found that I would get namespace issues, even though `ninja test` would pass OK.

```
simon@avid-test:~/libhinoko-github/samples$ ./iso-resource
Traceback (most recent call last):
  File "./iso-resource", line 5, in <module>
    gi.require_version('Hinoko', '0.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Hinoko not available
```

Turns out that Python does not like binaries/libraies being placed under '/usr/local' and you need to specify a prefix to meson.
`$ meson --prefix /usr build .`

**Comment by takaswie** [comment]
Hi @mungewell ,

The place of GIR  files in root filesystem is dependent on each distributions. So it's easy to use `topic/debian` branch to generate deb packages and install them. For them, please refer to [my comment](https://github.com/takaswie/libhinoko/issues/2#issuecomment-670274794).

**Comment by takaswie** [comment]
I added a quick instruction at commit 5c661f7b3b1b6 ("add quick instruction about installation and gobject-introspection").
https://github.com/takaswie/libhinoko/commit/5c661f7b3b1b69d7df194cd922ee9b6b722f9418

I note that you can use libhinoko without installing by configure `GI_TYPELIB_PATH` and `LD_LIBRARY_PATH` environment variables so that libgirepository and ld can find typelib file and shared library itself.

Thanks.
