### ISSUE TITLE
Namesapce error

### ISSUE THREAD

**Issue by taehunk** [takaswie/libhinoko#8]
Hi!, i'm trying to using this cool library for firewire.

But, i does not resolve some errors as follows:

<pre>
<code>
Traceback (most recent call last):
  File "./iso-resource", line 5, in <module>
    gi.require_version('Hinoko', '0.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Hinoko not available
</code>
</pre>

How can i install the <code>Hinoko-0.0.typelib</code> for fixing it.

Thanks!

**Comment by takaswie** [comment]
Hi,

```
Traceback (most recent call last):
File "./iso-resource", line 5, in
gi.require_version('Hinoko', '0.0')
File "/usr/lib/python3/dist-packages/gi/init.py", line 130, in require_version
raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Hinoko not available
```

The error message comes from PyGObject.

I think you have already installed libhinoko shared library (`libhinoko.so`) by executing `ninja install` or `meson install`.
If so, current location of library and the typelib are not whete PyGObject expects. As a result, PyGObject fail to find the typelib.
The typelib is important since it gives metadata of the shared library. PyGObject constructs API call procedure dynamically
according to the metadata so that the functions of library are available from Python script.

Do you check the location? The easiest way is to execute the installation procedure again.

Additionally I'd like to know the distribution you use.

Cheers.

**Comment by taehunk** [comment]
Thank for your response.

According to your comment, i checked the location of <code>Hinoko-0.0.typelib</code>.
In my system configuration,  <code>Hinoko-0.0.typelib</code> is placed in <code>/usr/local/lib/x86_64-linux-gnu/girepository-1.0/Hinoko-0.0.typelib</code>.

Therefore, i reconfigured the <code>GI_TYPELIB_PATH</code> and <code>LD_LIBRARY_PATH</code>. 
<code>export GI_TYPELIB_PATH=/usr/local/lib/x86_64-linux-gnu/girepository-1.0</code>
<code>export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/girepository-1.0</code>

However, i still met the error same as before.

How can i fix this error?

Oh. I'm using Ubuntu 18.04 with 5.4.0 version of kernel.

Best Regards.

**Comment by taehunk** [comment]
Hi, 

Today, I resolved this problem using this command (<code>$ meson --prefix /usr build .</code>).

Best Regards.

**Comment by takaswie** [comment]
Thankls for the information.

```
According to your comment, i checked the location of Hinoko-0.0.typelib.
In my system configuration, Hinoko-0.0.typelib is placed in /usr/local/lib/x86_64-linux-gnu/girepository-1.0/Hinoko-0.0.typelib.

Therefore, i reconfigured the GI_TYPELIB_PATH and LD_LIBRARY_PATH.
export GI_TYPELIB_PATH=/usr/local/lib/x86_64-linux-gnu/girepository-1.0
export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/girepository-1.0

However, i still met the error same as before.

How can i fix this error?

Oh. I'm using Ubuntu 18.04 with 5.4.0 version of kernel.
```

Indeed. I can regenerate your issue in LXC 3.0 container for bionic. As long as checking PyGObject namespace loading (precisely function in libgirepository-1.0.so), no matter of container or real machine.

When installing things under `/usr`, everything goes well. On the other hand, when installing things under `/usr/local`, the issue raises. I think we hit some issues of `libgirepository-1.0-1 1.56.1-1` (or former) or `python3-gi 3.26.1-2ubuntu1` (or former) but I have no idea, sorry...

I suppose two workarounds:

1. install under `/usr`

When configure meson build system with `--prefix=/usr` instead of `--prefix=/usr/local`,
the issue disappears, like:

```
$ meson --prefix=/usr . build
$ cd build
$ sudo ninja install
```

2. indicate `GI_TYPELIB_PATH` and `LD_LIBRARY_PATH` for stuffs in build directory without installation

GI_TYPELIB_PATH adds path to find typelib and LD_LIBRARY_PATH adds path to find shared library. You can use them for stuffs in build directory without installation, like:

```
$ meson . build
$ cd build
$ ninja
$ GI_TYPELIB_PATH=$(pwd)/src LD_LIBRARY_PATH=$(pwd)/src ../samples/iso-resource
```

Cheers

**Comment by takaswie** [comment]
> Today, I resolved this problem using this command (`$ meson --prefix /usr build .`).

Oh, we just crossed ;) Anyway it's nice for you to find the workaround by yourself.

If being familiar with deb packaging, `topic/debian` branch is useful, like:

```
$ git checkout origin/topic/debian -b topic/debian
$ dpkg-buildpackage -rfakeroot -uc -b
```

You can find deb packages in the upper directory.

Regards

**Comment by taehunk** [comment]
Thank you for the kind explanation.

Now, I can start playing with the firewire, using libhinoko. Thanks.

Have a nice day.

Cheers

**Comment by takaswie** [comment]
> Thank you for the kind explanation.
> 
> Now, I can start playing with the firewire, using libhinoko. Thanks.
> 
> Have a nice day.
> 
> Cheers

I'm glad to hear it.

I mention about [libhinawa](https://github.com/alsa-project/libhinawa), which is available to initiate asynchronous transaction in IEEE 1394 bus. The library is written with GObject Introspection support as well.

Let me close the issue. Thanks.
